# 应用服务 WEB 访问端口
server:
  port: 8989

spring:
  datasource:
    url: jdbc:mysql://123.57.194.64:3306/codeexplorer?serverTimeZone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: 33574183531
    driver-class-name: com.mysql.cj.jdbc.Driver


logging:
  config: classpath:logConfig/logback.xml

# mybatis相关配置
mybatis:
  type-aliases-package: com.hdu.edu.codeexplorer.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    cache-enabled: true